# This is the hw.tcl file for 'DF_fixp16_alu_av_FOC'
# Generated by High Level Design Compiler for Altera(R) FPGAs 

package require -exact qsys 14.1

# module DF_fixp16_alu_av_FOC
set_module_property NAME DF_fixp16_alu_av_FOC
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "DSP Builder Advanced"
set_module_property DISPLAY_NAME DF_fixp16_alu_av_FOC
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL DF_fixp16_alu_av_FOC

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_safe_path_flat.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_safe_path_flat.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC.vhd" VHDL PATH "DF_fixp16_alu_av_FOC.vhd"
	add_fileset_file "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd" VHDL PATH "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_fb_latches.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_fb_latches.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_FL_fixp16.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL DF_fixp16_alu_av_FOC

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_safe_path_flat.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_safe_path_flat.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC.vhd" VHDL PATH "DF_fixp16_alu_av_FOC.vhd"
	add_fileset_file "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd" VHDL PATH "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_fb_latches.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_fb_latches.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_FL_fixp16.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL DF_fixp16_alu_av_FOC

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "../Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_safe_path_flat.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_safe_path_flat.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC.vhd" VHDL PATH "DF_fixp16_alu_av_FOC.vhd"
	add_fileset_file "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd" VHDL PATH "busFabric_DF_fixp16_alu_av_FOC_217ipvmsy06j62696x6g656u0qu5xgbvsfqz.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_fb_latches.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_fb_latches.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_Avalon_Regs.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16.vhd" VHDL PATH "DF_fixp16_alu_av_FOC_FL_fixp16.vhd"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid292_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid295_Trig_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_sinPiAT_uid339_Trig2_lutmem.hex"
	add_fileset_file "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex" HEX PATH "DF_fixp16_alu_av_FOC_FL_fixp16_cosPiAT_uid342_Trig2_lutmem.hex"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1

# Interface clock_reset
add_interface clock_reset reset end
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset ASSOCIATED_CLOCK clock
add_interface_port clock_reset areset reset Input 1

# Interface bus_reset
add_interface bus_reset reset end
set_interface_property bus_reset ENABLED true
set_interface_property bus_reset ASSOCIATED_CLOCK clock
add_interface_port bus_reset h_areset reset Input 1

# Interface bus
add_interface bus avalon slave
set_interface_property bus maximumPendingReadTransactions 1
set_interface_property bus setupTime 0
set_interface_property bus ASSOCIATED_CLOCK clock
set_interface_property bus ENABLED true
add_interface_port bus busIn_address address Input 6
add_interface_port bus busIn_read read Input 1
set_port_property busIn_read VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_write write Input 1
set_port_property busIn_write VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_writedata writedata Input 32
add_interface_port bus busOut_readdata readdata Output 32
add_interface_port bus busOut_readdatavalid readdatavalid Output 1
set_port_property busOut_readdatavalid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busOut_waitrequest waitrequest Output 1
set_port_property busOut_waitrequest VHDL_TYPE STD_LOGIC_VECTOR

# Interface exp
add_interface exp conduit end
set_interface_property exp ENABLED true
add_interface_port exp Iu data_Iu Input 16
add_interface_port exp Iw data_Iw Input 16
add_interface_port exp vu_pwm data_vu_pwm Output 16
add_interface_port exp vv_pwm data_vv_pwm Output 16
add_interface_port exp vw_pwm data_vw_pwm Output 16
