/* ##################################################################################
 * Copyright (C) Altera Corporation
 *
 * This software and the related documents are Altera copyrighted materials, and
 * your use of them is governed by the express license under which they were
 * provided to you ("License"). Unless the License provides otherwise, you may
 * not use, modify, copy, publish, distribute, disclose or transmit this software
 * or the related documents without Altera's prior written permission.
 *
 * This software and the related documents are provided as is, with no express
 * or implied warranties, other than those that are expressly stated in the License.
 * ##################################################################################
 */

#ifndef __SYSTEM_SHIM_H_
#define __SYSTEM_SHIM_H_

/*
 * control_subsystem1_svm_dump configuration
 *
 */

#define ALT_MODULE_CLASS_svm_dump                       ALT_MODULE_CLASS_control_subsystem1_doc_svm_dump
#define SVM_DUMP_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR  CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR
#define SVM_DUMP_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE      CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE
#define SVM_DUMP_BASE                                   CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_BASE
#define SVM_DUMP_CONTENTS_INFO                          CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_CONTENTS_INFO
#define SVM_DUMP_DUAL_PORT                              CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_DUAL_PORT
#define SVM_DUMP_GUI_RAM_BLOCK_TYPE                     CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_GUI_RAM_BLOCK_TYPE
#define SVM_DUMP_INIT_CONTENTS_FILE                     CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_INIT_CONTENTS_FILE
#define SVM_DUMP_INIT_MEM_CONTENT                       CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_INIT_MEM_CONTENT
#define SVM_DUMP_INSTANCE_ID                            CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_INSTANCE_ID
#define SVM_DUMP_IRQ                                    CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_IRQ
#define SVM_DUMP_IRQ_INTERRUPT_CONTROLLER_ID            CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_IRQ_INTERRUPT_CONTROLLER_ID
#define SVM_DUMP_NAME                                   CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_NAME
#define SVM_DUMP_NON_DEFAULT_INIT_FILE_ENABLED          CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_NON_DEFAULT_INIT_FILE_ENABLED
#define SVM_DUMP_RAM_BLOCK_TYPE                         CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_RAM_BLOCK_TYPE
#define SVM_DUMP_READ_DURING_WRITE_MODE                 CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_READ_DURING_WRITE_MODE
#define SVM_DUMP_SINGLE_CLOCK_OP                        CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_SINGLE_CLOCK_OP
#define SVM_DUMP_SIZE_MULTIPLE                          CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_SIZE_MULTIPLE
#define SVM_DUMP_SIZE_VALUE                             CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_SIZE_VALUE
#define SVM_DUMP_SPAN                                   CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_SPAN
#define SVM_DUMP_TYPE                                   CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_TYPE
#define SVM_DUMP_WRITABLE                               CONTROL_SUBSYSTEM1_DOC_SVM_DUMP_WRITABLE


/*
 * control_subsystem1_sys_console_debug_ram configuration
 *
 */

#define ALT_MODULE_CLASS_sys_console_debug_ram                      ALT_MODULE_CLASS_control_subsystem1_doc_sys_console_debug_ram
#define SYS_CONSOLE_DEBUG_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR
#define SYS_CONSOLE_DEBUG_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE     CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE
#define SYS_CONSOLE_DEBUG_RAM_BASE                                  CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_BASE
#define SYS_CONSOLE_DEBUG_RAM_CONTENTS_INFO                         CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_CONTENTS_INFO
#define SYS_CONSOLE_DEBUG_RAM_DUAL_PORT                             CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_DUAL_PORT
#define SYS_CONSOLE_DEBUG_RAM_GUI_RAM_BLOCK_TYPE                    CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_GUI_RAM_BLOCK_TYPE
#define SYS_CONSOLE_DEBUG_RAM_INIT_CONTENTS_FILE                    CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_INIT_CONTENTS_FILE
#define SYS_CONSOLE_DEBUG_RAM_INIT_MEM_CONTENT                      CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_INIT_MEM_CONTENT
#define SYS_CONSOLE_DEBUG_RAM_INSTANCE_ID                           CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_INSTANCE_ID
#define SYS_CONSOLE_DEBUG_RAM_IRQ                                   CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_IRQ
#define SYS_CONSOLE_DEBUG_RAM_IRQ_INTERRUPT_CONTROLLER_ID           CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_IRQ_INTERRUPT_CONTROLLER_ID
#define SYS_CONSOLE_DEBUG_RAM_NAME                                  CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_NAME
#define SYS_CONSOLE_DEBUG_RAM_NON_DEFAULT_INIT_FILE_ENABLED         CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_NON_DEFAULT_INIT_FILE_ENABLED
#define SYS_CONSOLE_DEBUG_RAM_RAM_BLOCK_TYPE                        CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_RAM_BLOCK_TYPE
#define SYS_CONSOLE_DEBUG_RAM_READ_DURING_WRITE_MODE                CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_READ_DURING_WRITE_MODE
#define SYS_CONSOLE_DEBUG_RAM_SINGLE_CLOCK_OP                       CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_SINGLE_CLOCK_OP
#define SYS_CONSOLE_DEBUG_RAM_SIZE_MULTIPLE                         CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_SIZE_MULTIPLE
#define SYS_CONSOLE_DEBUG_RAM_SIZE_VALUE                            CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_SIZE_VALUE
#define SYS_CONSOLE_DEBUG_RAM_SPAN                                  CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_SPAN
#define SYS_CONSOLE_DEBUG_RAM_TYPE                                  CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_TYPE
#define SYS_CONSOLE_DEBUG_RAM_WRITABLE                              CONTROL_SUBSYSTEM1_DOC_SYS_CONSOLE_DEBUG_RAM_WRITABLE


/*
 * dniosv_subsystem1_cpu_timer configuration
 *
 */

#define ALT_MODULE_CLASS_cpu_timer             ALT_MODULE_CLASS_dniosv_subsystem1_cpu_timer
#define DOC_TMR_0_ALWAYS_RUN                   DNIOSV_SUBSYSTEM1_CPU_TIMER_ALWAYS_RUN
#define DOC_TMR_0_BASE                         DNIOSV_SUBSYSTEM1_CPU_TIMER_BASE
#define DOC_TMR_0_COUNTER_SIZE                 DNIOSV_SUBSYSTEM1_CPU_TIMER_COUNTER_SIZE
#define DOC_TMR_0_FIXED_PERIOD                 DNIOSV_SUBSYSTEM1_CPU_TIMER_FIXED_PERIOD
#define DOC_TMR_0_FREQ                         DNIOSV_SUBSYSTEM1_CPU_TIMER_FREQ
#define DOC_TMR_0_IRQ                          DNIOSV_SUBSYSTEM1_CPU_TIMER_IRQ
#define DOC_TMR_0_IRQ_INTERRUPT_CONTROLLER_ID  DNIOSV_SUBSYSTEM1_CPU_TIMER_IRQ_INTERRUPT_CONTROLLER_ID
#define DOC_TMR_0_LOAD_VALUE                   DNIOSV_SUBSYSTEM1_CPU_TIMER_LOAD_VALUE
#define DOC_TMR_0_MULT                         DNIOSV_SUBSYSTEM1_CPU_TIMER_MULT
#define DOC_TMR_0_NAME                         DNIOSV_SUBSYSTEM1_CPU_TIMER_NAME
#define DOC_TMR_0_PERIOD                       DNIOSV_SUBSYSTEM1_CPU_TIMER_PERIOD
#define DOC_TMR_0_PERIOD_UNITS                 DNIOSV_SUBSYSTEM1_CPU_TIMER_PERIOD_UNITS
#define DOC_TMR_0_RESET_OUTPUT                 DNIOSV_SUBSYSTEM1_CPU_TIMER_RESET_OUTPUT
#define DOC_TMR_0_SNAPSHOT                     DNIOSV_SUBSYSTEM1_CPU_TIMER_SNAPSHOT
#define DOC_TMR_0_SPAN                         DNIOSV_SUBSYSTEM1_CPU_TIMER_SPAN
#define DOC_TMR_0_TICKS_PER_SEC                DNIOSV_SUBSYSTEM1_CPU_TIMER_TICKS_PER_SEC
#define DOC_TMR_0_TIMEOUT_PULSE_OUTPUT         DNIOSV_SUBSYSTEM1_CPU_TIMER_TIMEOUT_PULSE_OUTPUT
#define DOC_TMR_0_TIMER_DEVICE_TYPE            DNIOSV_SUBSYSTEM1_CPU_TIMER_TIMER_DEVICE_TYPE
#define DOC_TMR_0_TYPE                         DNIOSV_SUBSYSTEM1_CPU_TIMER_TYPE


/*
 * dniosv_subsystem1_doc_tmr_1 configuration
 *
 */

#define ALT_MODULE_CLASS_doc_tmr_1                       ALT_MODULE_CLASS_dniosv_subsystem1_doc_tmr_1
#define DOC_TMR_1_ALWAYS_RUN                             DNIOSV_SUBSYSTEM1_DOC_TMR_1_ALWAYS_RUN
#define DOC_TMR_1_BASE                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_BASE
#define DOC_TMR_1_COUNTER_SIZE                           DNIOSV_SUBSYSTEM1_DOC_TMR_1_COUNTER_SIZE
#define DOC_TMR_1_FIXED_PERIOD                           DNIOSV_SUBSYSTEM1_DOC_TMR_1_FIXED_PERIOD
#define DOC_TMR_1_FREQ                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_FREQ
#define DOC_TMR_1_IRQ                                    DNIOSV_SUBSYSTEM1_DOC_TMR_1_IRQ
#define DOC_TMR_1_IRQ_INTERRUPT_CONTROLLER_ID            DNIOSV_SUBSYSTEM1_DOC_TMR_1_IRQ_INTERRUPT_CONTROLLER_ID
#define DOC_TMR_1_LOAD_VALUE                             DNIOSV_SUBSYSTEM1_DOC_TMR_1_LOAD_VALUE
#define DOC_TMR_1_MULT                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_MULT
#define DOC_TMR_1_NAME                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_NAME
#define DOC_TMR_1_PERIOD                                 DNIOSV_SUBSYSTEM1_DOC_TMR_1_PERIOD
#define DOC_TMR_1_PERIOD_UNITS                           DNIOSV_SUBSYSTEM1_DOC_TMR_1_PERIOD_UNITS
#define DOC_TMR_1_RESET_OUTPUT                           DNIOSV_SUBSYSTEM1_DOC_TMR_1_RESET_OUTPUT
#define DOC_TMR_1_SNAPSHOT                               DNIOSV_SUBSYSTEM1_DOC_TMR_1_SNAPSHOT
#define DOC_TMR_1_SPAN                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_SPAN
#define DOC_TMR_1_TICKS_PER_SEC                          DNIOSV_SUBSYSTEM1_DOC_TMR_1_TICKS_PER_SEC
#define DOC_TMR_1_TIMEOUT_PULSE_OUTPUT                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_TIMEOUT_PULSE_OUTPUT
#define DOC_TMR_1_TIMER_DEVICE_TYPE                      DNIOSV_SUBSYSTEM1_DOC_TMR_1_TIMER_DEVICE_TYPE
#define DOC_TMR_1_TYPE                                   DNIOSV_SUBSYSTEM1_DOC_TMR_1_TYPE


/*
 * dniosv_subsystem1_cpu_jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart              ALT_MODULE_CLASS_dniosv_subsystem1_cpu_jtag_uart
#define JTAG_UART_BASE                          DNIOSV_SUBSYSTEM1_JTAG_UART_BASE
#define JTAG_UART_IRQ                           DNIOSV_SUBSYSTEM1_JTAG_UART_IRQ
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID   DNIOSV_SUBSYSTEM1_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID
#define JTAG_UART_NAME                          DNIOSV_SUBSYSTEM1_JTAG_UART_NAME
#define JTAG_UART_READ_DEPTH                    DNIOSV_SUBSYSTEM1_JTAG_UART_READ_DEPTH
#define JTAG_UART_READ_THRESHOLD                DNIOSV_SUBSYSTEM1_JTAG_UART_READ_THRESHOLD
#define JTAG_UART_SPAN                          DNIOSV_SUBSYSTEM1_JTAG_UART_SPAN
#define JTAG_UART_TYPE                          DNIOSV_SUBSYSTEM1_JTAG_UART_TYPE
#define JTAG_UART_WRITE_DEPTH                   DNIOSV_SUBSYSTEM1_JTAG_UART_WRITE_DEPTH
#define JTAG_UART_WRITE_THRESHOLD               DNIOSV_SUBSYSTEM1_JTAG_UART_WRITE_THRESHOLD


/*
 * dniosv_subsystem1_cpu_ram configuration
 *
 */

#define ALT_MODULE_CLASS_cpu_ram                                ALT_MODULE_CLASS_dniosv_subsystem1_cpu_ram
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR  DNIOSV_SUBSYSTEM1_CPU_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE      DNIOSV_SUBSYSTEM1_CPU_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE
#define ONCHIP_MEMORY2_0_BASE                                   DNIOSV_SUBSYSTEM1_CPU_RAM_BASE
#define ONCHIP_MEMORY2_0_CONTENTS_INFO                          DNIOSV_SUBSYSTEM1_CPU_RAM_CONTENTS_INFO
#define ONCHIP_MEMORY2_0_DUAL_PORT                              DNIOSV_SUBSYSTEM1_CPU_RAM_DUAL_PORT
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE                     DNIOSV_SUBSYSTEM1_CPU_RAM_GUI_RAM_BLOCK_TYPE
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE                     DNIOSV_SUBSYSTEM1_CPU_RAM_INIT_CONTENTS_FILE
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT                       DNIOSV_SUBSYSTEM1_CPU_RAM_INIT_MEM_CONTENT
#define ONCHIP_MEMORY2_0_INSTANCE_ID                            DNIOSV_SUBSYSTEM1_CPU_RAM_INSTANCE_ID
#define ONCHIP_MEMORY2_0_IRQ                                    DNIOSV_SUBSYSTEM1_CPU_RAM_IRQ
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID            DNIOSV_SUBSYSTEM1_CPU_RAM_IRQ_INTERRUPT_CONTROLLER_ID
#define ONCHIP_MEMORY2_0_NAME                                   DNIOSV_SUBSYSTEM1_CPU_RAM_NAME
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED          DNIOSV_SUBSYSTEM1_CPU_RAM_NON_DEFAULT_INIT_FILE_ENABLED
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE                         DNIOSV_SUBSYSTEM1_CPU_RAM_RAM_BLOCK_TYPE
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE                 DNIOSV_SUBSYSTEM1_CPU_RAM_READ_DURING_WRITE_MODE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP                        DNIOSV_SUBSYSTEM1_CPU_RAM_SINGLE_CLOCK_OP
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE                          DNIOSV_SUBSYSTEM1_CPU_RAM_SIZE_MULTIPLE
#define ONCHIP_MEMORY2_0_SIZE_VALUE                             DNIOSV_SUBSYSTEM1_CPU_RAM_SIZE_VALUE
#define ONCHIP_MEMORY2_0_SPAN                                   DNIOSV_SUBSYSTEM1_CPU_RAM_SPAN
#define ONCHIP_MEMORY2_0_TYPE                                   DNIOSV_SUBSYSTEM1_CPU_RAM_TYPE
#define ONCHIP_MEMORY2_0_WRITABLE                               DNIOSV_SUBSYSTEM1_CPU_RAM_WRITABLE


/*
 * dniosv_subsystem1_performance_counter_0 configuration
 *
 */

#define ALT_MODULE_CLASS_performance_counter_0              ALT_MODULE_CLASS_dniosv_subsystem1_performance_counter_0
#define PERFORMANCE_COUNTER_0_BASE                          DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_BASE
#define PERFORMANCE_COUNTER_0_HOW_MANY_SECTIONS             DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_HOW_MANY_SECTIONS
#define PERFORMANCE_COUNTER_0_IRQ                           DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_IRQ
#define PERFORMANCE_COUNTER_0_IRQ_INTERRUPT_CONTROLLER_ID   DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_IRQ_INTERRUPT_CONTROLLER_ID
#define PERFORMANCE_COUNTER_0_NAME                          DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_NAME
#define PERFORMANCE_COUNTER_0_SPAN                          DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_SPAN
#define PERFORMANCE_COUNTER_0_TYPE                          DNIOSV_SUBSYSTEM1_PERFORMANCE_COUNTER_0_TYPE


/*
 * dniosv_subsystem1_sysid_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_0            ALT_MODULE_CLASS_dniosv_subsystem1_sysid_0
#define SYSID_0_BASE                        DNIOSV_SUBSYSTEM1_SYSID_0_BASE
#define SYSID_0_ID                          DNIOSV_SUBSYSTEM1_SYSID_0_ID
#define SYSID_0_IRQ                         DNIOSV_SUBSYSTEM1_SYSID_0_IRQ
#define SYSID_0_IRQ_INTERRUPT_CONTROLLER_ID DNIOSV_SUBSYSTEM1_SYSID_0_IRQ_INTERRUPT_CONTROLLER_ID
#define SYSID_0_NAME                        DNIOSV_SUBSYSTEM1_SYSID_0_NAME
#define SYSID_0_SPAN                        DNIOSV_SUBSYSTEM1_SYSID_0_SPAN
#define SYSID_0_TIMESTAMP                   DNIOSV_SUBSYSTEM1_SYSID_0_TIMESTAMP
#define SYSID_0_TYPE                        DNIOSV_SUBSYSTEM1_SYSID_0_TYPE


/*
 * drive_subsystem_2_DOC_ADC configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_DOC_ADC                ALT_MODULE_CLASS_drive_subsystem_2_doc_adc
#define DRIVE0_DOC_ADC_BASE                            DRIVE_SUBSYSTEM_2_DOC_ADC_BASE
#define DRIVE0_DOC_ADC_IRQ                             DRIVE_SUBSYSTEM_2_DOC_ADC_IRQ
#define DRIVE0_DOC_ADC_IRQ_INTERRUPT_CONTROLLER_ID     DRIVE_SUBSYSTEM_2_DOC_ADC_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_ADC_NAME                            DRIVE_SUBSYSTEM_2_DOC_ADC_NAME
#define DRIVE0_DOC_ADC_SPAN                            DRIVE_SUBSYSTEM_2_DOC_ADC_SPAN
#define DRIVE0_DOC_ADC_TYPE                            DRIVE_SUBSYSTEM_2_DOC_ADC_TYPE


/*
 * drive_subsystem_2_DOC_ADC_POW configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_DOC_ADC_POW                   ALT_MODULE_CLASS_drive_subsystem_2_doc_adc_pow
#define DRIVE0_DOC_ADC_POW_BASE                               DRIVE_SUBSYSTEM_2_DOC_ADC_POW_BASE
#define DRIVE0_DOC_ADC_POW_IRQ                                DRIVE_SUBSYSTEM_2_DOC_ADC_POW_IRQ
#define DRIVE0_DOC_ADC_POW_IRQ_INTERRUPT_CONTROLLER_ID        DRIVE_SUBSYSTEM_2_DOC_ADC_POW_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_ADC_POW_NAME                               DRIVE_SUBSYSTEM_2_DOC_ADC_POW_NAME
#define DRIVE0_DOC_ADC_POW_SPAN                               DRIVE_SUBSYSTEM_2_DOC_ADC_POW_SPAN
#define DRIVE0_DOC_ADC_POW_TYPE                               DRIVE_SUBSYSTEM_2_DOC_ADC_POW_TYPE


/*
 * drive_subsystem_2_DOC_PWM configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_DOC_PWM                    ALT_MODULE_CLASS_drive_subsystem_2_doc_pwm
#define DRIVE0_DOC_PWM_BASE                                DRIVE_SUBSYSTEM_2_DOC_PWM_BASE
#define DRIVE0_DOC_PWM_FREQ                                DRIVE_SUBSYSTEM_2_DOC_PWM_FREQ
#define DRIVE0_DOC_PWM_IRQ                                 DRIVE_SUBSYSTEM_2_DOC_PWM_IRQ
#define DRIVE0_DOC_PWM_IRQ_INTERRUPT_CONTROLLER_ID         DRIVE_SUBSYSTEM_2_DOC_PWM_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_PWM_NAME                                DRIVE_SUBSYSTEM_2_DOC_PWM_NAME
#define DRIVE0_DOC_PWM_SPAN                                DRIVE_SUBSYSTEM_2_DOC_PWM_SPAN
#define DRIVE0_DOC_PWM_TYPE                                DRIVE_SUBSYSTEM_2_DOC_PWM_TYPE


/*
 * drive_subsystem_2_DOC_QEP configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_DOC_QEP                     ALT_MODULE_CLASS_drive_subsystem_2_doc_qep
#define DRIVE0_DOC_QEP_BASE                                 DRIVE_SUBSYSTEM_2_DOC_QEP_BASE
#define DRIVE0_DOC_QEP_IRQ                                  DRIVE_SUBSYSTEM_2_DOC_QEP_IRQ
#define DRIVE0_DOC_QEP_IRQ_INTERRUPT_CONTROLLER_ID          DRIVE_SUBSYSTEM_2_DOC_QEP_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_QEP_NAME                                 DRIVE_SUBSYSTEM_2_DOC_QEP_NAME
#define DRIVE0_DOC_QEP_SPAN                                 DRIVE_SUBSYSTEM_2_DOC_QEP_SPAN
#define DRIVE0_DOC_QEP_TYPE                                 DRIVE_SUBSYSTEM_2_DOC_QEP_TYPE


/*
 * drive_subsystem_2_DOC_SM configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_DOC_SM                        ALT_MODULE_CLASS_drive_subsystem_2_doc_sm
#define DRIVE0_DOC_SM_BASE                                    DRIVE_SUBSYSTEM_2_DOC_SM_BASE
#define DRIVE0_DOC_SM_IRQ                                     DRIVE_SUBSYSTEM_2_DOC_SM_IRQ
#define DRIVE0_DOC_SM_IRQ_INTERRUPT_CONTROLLER_ID             DRIVE_SUBSYSTEM_2_DOC_SM_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_SM_NAME                                    DRIVE_SUBSYSTEM_2_DOC_SM_NAME
#define DRIVE0_DOC_SM_SPAN                                    DRIVE_SUBSYSTEM_2_DOC_SM_SPAN
#define DRIVE0_DOC_SM_TYPE                                    DRIVE_SUBSYSTEM_2_DOC_SM_TYPE


/*
 * drive_subsystem_2_FOC_Fixp configuration
 *
 */

#define ALT_MODULE_CLASS_drive0_FOC_Fixp                        ALT_MODULE_CLASS_drive_subsystem_2_doc_foc_fixp
#define DRIVE0_FOC_FIXP_BASE                                    DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_BASE
#define DRIVE0_FOC_FIXP_IRQ                                     DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_IRQ
#define DRIVE0_FOC_FIXP_IRQ_INTERRUPT_CONTROLLER_ID             DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_FOC_FIXP_NAME                                    DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_NAME
#define DRIVE0_FOC_FIXP_SPAN                                    DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_SPAN
#define DRIVE0_FOC_FIXP_TYPE                                    DRIVE_SUBSYSTEM_2_DOC_FOC_FIXP_TYPE


/*
 * drive_subsystem_2_doc_rslvr_pio configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_pio
#define ALT_MODULE_CLASS_drive0_doc_rslvr_pio                    ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_pio
#define DRIVE0_DOC_RSLVR_PIO_BASE                                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_BASE
#define DRIVE0_DOC_RSLVR_PIO_BIT_CLEARING_EDGE_REGISTER          DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_BIT_CLEARING_EDGE_REGISTER
#define DRIVE0_DOC_RSLVR_PIO_BIT_MODIFYING_OUTPUT_REGISTER       DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_BIT_MODIFYING_OUTPUT_REGISTER
#define DRIVE0_DOC_RSLVR_PIO_CAPTURE                             DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_CAPTURE
#define DRIVE0_DOC_RSLVR_PIO_DATA_WIDTH                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_DATA_WIDTH
#define DRIVE0_DOC_RSLVR_PIO_DO_TEST_BENCH_WIRING                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_DO_TEST_BENCH_WIRING
#define DRIVE0_DOC_RSLVR_PIO_DRIVEN_SIM_VALUE                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_DRIVEN_SIM_VALUE
#define DRIVE0_DOC_RSLVR_PIO_EDGE_TYPE                           DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_EDGE_TYPE
#define DRIVE0_DOC_RSLVR_PIO_FREQ                                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_FREQ
#define DRIVE0_DOC_RSLVR_PIO_HAS_IN                              DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_HAS_IN
#define DRIVE0_DOC_RSLVR_PIO_HAS_OUT                             DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_HAS_OUT
#define DRIVE0_DOC_RSLVR_PIO_HAS_TRI                             DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_HAS_TRI
#define DRIVE0_DOC_RSLVR_PIO_IRQ                                 DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_IRQ
#define DRIVE0_DOC_RSLVR_PIO_IRQ_INTERRUPT_CONTROLLER_ID         DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_RSLVR_PIO_IRQ_TYPE                            DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_IRQ_TYPE
#define DRIVE0_DOC_RSLVR_PIO_NAME                                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_NAME
#define DRIVE0_DOC_RSLVR_PIO_RESET_VALUE                         DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_RESET_VALUE
#define DRIVE0_DOC_RSLVR_PIO_SPAN                                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_SPAN
#define DRIVE0_DOC_RSLVR_PIO_TYPE                                DRIVE_SUBSYSTEM_2_DOC_RSLVR_PIO_TYPE
#endif

/*
 * drive_subsystem_2_doc_rslvr_spi_ctrl configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_spi_ctrl
#define ALT_MODULE_CLASS_drive0_doc_rslvr_spi_ctrl              ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_spi_ctrl
#define DRIVE0_DOC_RSLVR_SPI_CTRL_BASE                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_BASE
#define DRIVE0_DOC_RSLVR_SPI_CTRL_CLOCKMULT                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_CLOCKMULT
#define DRIVE0_DOC_RSLVR_SPI_CTRL_CLOCKPHASE                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_CLOCKPHASE
#define DRIVE0_DOC_RSLVR_SPI_CTRL_CLOCKPOLARITY                 DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_CLOCKPOLARITY
#define DRIVE0_DOC_RSLVR_SPI_CTRL_CLOCKUNITS                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_CLOCKUNITS
#define DRIVE0_DOC_RSLVR_SPI_CTRL_DATABITS                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_DATABITS
#define DRIVE0_DOC_RSLVR_SPI_CTRL_DATAWIDTH                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_DATAWIDTH
#define DRIVE0_DOC_RSLVR_SPI_CTRL_DELAYMULT                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_DELAYMULT
#define DRIVE0_DOC_RSLVR_SPI_CTRL_DELAYUNITS                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_DELAYUNITS
#define DRIVE0_DOC_RSLVR_SPI_CTRL_EXTRADELAY                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_EXTRADELAY
#define DRIVE0_DOC_RSLVR_SPI_CTRL_INSERT_SYNC                   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_INSERT_SYNC
#define DRIVE0_DOC_RSLVR_SPI_CTRL_IRQ                           DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_IRQ
#define DRIVE0_DOC_RSLVR_SPI_CTRL_IRQ_INTERRUPT_CONTROLLER_ID   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_RSLVR_SPI_CTRL_ISMASTER                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_ISMASTER
#define DRIVE0_DOC_RSLVR_SPI_CTRL_LSBFIRST                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_LSBFIRST
#define DRIVE0_DOC_RSLVR_SPI_CTRL_NAME                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_NAME
#define DRIVE0_DOC_RSLVR_SPI_CTRL_NUMSLAVES                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_NUMSLAVES
#define DRIVE0_DOC_RSLVR_SPI_CTRL_PREFIX                        DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_PREFIX
#define DRIVE0_DOC_RSLVR_SPI_CTRL_SPAN                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_SPAN
#define DRIVE0_DOC_RSLVR_SPI_CTRL_SYNC_REG_DEPTH                DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_SYNC_REG_DEPTH
#define DRIVE0_DOC_RSLVR_SPI_CTRL_TARGETCLOCK                   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_TARGETCLOCK
#define DRIVE0_DOC_RSLVR_SPI_CTRL_TARGETSSDELAY                 DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_TARGETSSDELAY
#define DRIVE0_DOC_RSLVR_SPI_CTRL_TYPE                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_CTRL_TYPE
#endif

/*
 * drive_subsystem_2_doc_rslvr_spi_posn configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_spi_posn
#define ALT_MODULE_CLASS_drive0_doc_rslvr_spi_posn              ALT_MODULE_CLASS_drive_subsystem_2_doc_rslvr_spi_posn
#define DRIVE0_DOC_RSLVR_SPI_POSN_BASE                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_BASE
#define DRIVE0_DOC_RSLVR_SPI_POSN_CLOCKMULT                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_CLOCKMULT
#define DRIVE0_DOC_RSLVR_SPI_POSN_CLOCKPHASE                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_CLOCKPHASE
#define DRIVE0_DOC_RSLVR_SPI_POSN_CLOCKPOLARITY                 DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_CLOCKPOLARITY
#define DRIVE0_DOC_RSLVR_SPI_POSN_CLOCKUNITS                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_CLOCKUNITS
#define DRIVE0_DOC_RSLVR_SPI_POSN_DATABITS                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_DATABITS
#define DRIVE0_DOC_RSLVR_SPI_POSN_DATAWIDTH                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_DATAWIDTH
#define DRIVE0_DOC_RSLVR_SPI_POSN_DELAYMULT                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_DELAYMULT
#define DRIVE0_DOC_RSLVR_SPI_POSN_DELAYUNITS                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_DELAYUNITS
#define DRIVE0_DOC_RSLVR_SPI_POSN_EXTRADELAY                    DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_EXTRADELAY
#define DRIVE0_DOC_RSLVR_SPI_POSN_INSERT_SYNC                   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_INSERT_SYNC
#define DRIVE0_DOC_RSLVR_SPI_POSN_IRQ                           DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_IRQ
#define DRIVE0_DOC_RSLVR_SPI_POSN_IRQ_INTERRUPT_CONTROLLER_ID   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_DOC_RSLVR_SPI_POSN_ISMASTER                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_ISMASTER
#define DRIVE0_DOC_RSLVR_SPI_POSN_LSBFIRST                      DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_LSBFIRST
#define DRIVE0_DOC_RSLVR_SPI_POSN_NAME                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_NAME
#define DRIVE0_DOC_RSLVR_SPI_POSN_NUMSLAVES                     DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_NUMSLAVES
#define DRIVE0_DOC_RSLVR_SPI_POSN_PREFIX                        DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_PREFIX
#define DRIVE0_DOC_RSLVR_SPI_POSN_SPAN                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_SPAN
#define DRIVE0_DOC_RSLVR_SPI_POSN_SYNC_REG_DEPTH                DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_SYNC_REG_DEPTH
#define DRIVE0_DOC_RSLVR_SPI_POSN_TARGETCLOCK                   DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_TARGETCLOCK
#define DRIVE0_DOC_RSLVR_SPI_POSN_TARGETSSDELAY                 DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_TARGETSSDELAY
#define DRIVE0_DOC_RSLVR_SPI_POSN_TYPE                          DRIVE_SUBSYSTEM_2_DOC_RSLVR_SPI_POSN_TYPE
#endif

/*
 * drive_subsystem_2_hall_pio configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_2_hall_pio
#define ALT_MODULE_CLASS_drive0_hall_pio                ALT_MODULE_CLASS_drive_subsystem_2_hall_pio
#define DRIVE0_HALL_PIO_BASE                            DRIVE_SUBSYSTEM_2_HALL_PIO_BASE
#define DRIVE0_HALL_PIO_BIT_CLEARING_EDGE_REGISTER      DRIVE_SUBSYSTEM_2_HALL_PIO_BIT_CLEARING_EDGE_REGISTER
#define DRIVE0_HALL_PIO_BIT_MODIFYING_OUTPUT_REGISTER   DRIVE_SUBSYSTEM_2_HALL_PIO_BIT_MODIFYING_OUTPUT_REGISTER
#define DRIVE0_HALL_PIO_CAPTURE                         DRIVE_SUBSYSTEM_2_HALL_PIO_CAPTURE
#define DRIVE0_HALL_PIO_DATA_WIDTH                      DRIVE_SUBSYSTEM_2_HALL_PIO_DATA_WIDTH
#define DRIVE0_HALL_PIO_DO_TEST_BENCH_WIRING            DRIVE_SUBSYSTEM_2_HALL_PIO_DO_TEST_BENCH_WIRING
#define DRIVE0_HALL_PIO_DRIVEN_SIM_VALUE                DRIVE_SUBSYSTEM_2_HALL_PIO_DRIVEN_SIM_VALUE
#define DRIVE0_HALL_PIO_EDGE_TYPE                       DRIVE_SUBSYSTEM_2_HALL_PIO_EDGE_TYPE
#define DRIVE0_HALL_PIO_FREQ                            DRIVE_SUBSYSTEM_2_HALL_PIO_FREQ
#define DRIVE0_HALL_PIO_HAS_IN                          DRIVE_SUBSYSTEM_2_HALL_PIO_HAS_IN
#define DRIVE0_HALL_PIO_HAS_OUT                         DRIVE_SUBSYSTEM_2_HALL_PIO_HAS_OUT
#define DRIVE0_HALL_PIO_HAS_TRI                         DRIVE_SUBSYSTEM_2_HALL_PIO_HAS_TRI
#define DRIVE0_HALL_PIO_IRQ                             DRIVE_SUBSYSTEM_2_HALL_PIO_IRQ
#define DRIVE0_HALL_PIO_IRQ_INTERRUPT_CONTROLLER_ID     DRIVE_SUBSYSTEM_2_HALL_PIO_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE0_HALL_PIO_IRQ_TYPE                        DRIVE_SUBSYSTEM_2_HALL_PIO_IRQ_TYPE
#define DRIVE0_HALL_PIO_NAME                            DRIVE_SUBSYSTEM_2_HALL_PIO_NAME
#define DRIVE0_HALL_PIO_RESET_VALUE                     DRIVE_SUBSYSTEM_2_HALL_PIO_RESET_VALUE
#define DRIVE0_HALL_PIO_SPAN                            DRIVE_SUBSYSTEM_2_HALL_PIO_SPAN
#define DRIVE0_HALL_PIO_TYPE                            DRIVE_SUBSYSTEM_2_HALL_PIO_TYPE
#endif
/*
 * drive_subsystem_3_DOC_ADC configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_DOC_ADC                ALT_MODULE_CLASS_drive_subsystem_3_doc_adc
#define DRIVE1_DOC_ADC_BASE                            DRIVE_SUBSYSTEM_3_DOC_ADC_BASE
#define DRIVE1_DOC_ADC_IRQ                             DRIVE_SUBSYSTEM_3_DOC_ADC_IRQ
#define DRIVE1_DOC_ADC_IRQ_INTERRUPT_CONTROLLER_ID     DRIVE_SUBSYSTEM_3_DOC_ADC_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_ADC_NAME                            DRIVE_SUBSYSTEM_3_DOC_ADC_NAME
#define DRIVE1_DOC_ADC_SPAN                            DRIVE_SUBSYSTEM_3_DOC_ADC_SPAN
#define DRIVE1_DOC_ADC_TYPE                            DRIVE_SUBSYSTEM_3_DOC_ADC_TYPE


/*
 * drive_subsystem_3_DOC_ADC_POW configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_DOC_ADC_POW                   ALT_MODULE_CLASS_drive_subsystem_3_doc_adc_pow
#define DRIVE1_DOC_ADC_POW_BASE                               DRIVE_SUBSYSTEM_3_DOC_ADC_POW_BASE
#define DRIVE1_DOC_ADC_POW_IRQ                                DRIVE_SUBSYSTEM_3_DOC_ADC_POW_IRQ
#define DRIVE1_DOC_ADC_POW_IRQ_INTERRUPT_CONTROLLER_ID        DRIVE_SUBSYSTEM_3_DOC_ADC_POW_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_ADC_POW_NAME                               DRIVE_SUBSYSTEM_3_DOC_ADC_POW_NAME
#define DRIVE1_DOC_ADC_POW_SPAN                               DRIVE_SUBSYSTEM_3_DOC_ADC_POW_SPAN
#define DRIVE1_DOC_ADC_POW_TYPE                               DRIVE_SUBSYSTEM_3_DOC_ADC_POW_TYPE


/*
 * drive_subsystem_3_DOC_PWM configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_DOC_PWM                    ALT_MODULE_CLASS_drive_subsystem_3_doc_pwm
#define DRIVE1_DOC_PWM_BASE                                DRIVE_SUBSYSTEM_3_DOC_PWM_BASE
#define DRIVE1_DOC_PWM_FREQ                                DRIVE_SUBSYSTEM_3_DOC_PWM_FREQ
#define DRIVE1_DOC_PWM_IRQ                                 DRIVE_SUBSYSTEM_3_DOC_PWM_IRQ
#define DRIVE1_DOC_PWM_IRQ_INTERRUPT_CONTROLLER_ID         DRIVE_SUBSYSTEM_3_DOC_PWM_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_PWM_NAME                                DRIVE_SUBSYSTEM_3_DOC_PWM_NAME
#define DRIVE1_DOC_PWM_SPAN                                DRIVE_SUBSYSTEM_3_DOC_PWM_SPAN
#define DRIVE1_DOC_PWM_TYPE                                DRIVE_SUBSYSTEM_3_DOC_PWM_TYPE


/*
 * drive_subsystem_3_DOC_QEP configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_DOC_QEP                     ALT_MODULE_CLASS_drive_subsystem_3_doc_qep
#define DRIVE1_DOC_QEP_BASE                                 DRIVE_SUBSYSTEM_3_DOC_QEP_BASE
#define DRIVE1_DOC_QEP_IRQ                                  DRIVE_SUBSYSTEM_3_DOC_QEP_IRQ
#define DRIVE1_DOC_QEP_IRQ_INTERRUPT_CONTROLLER_ID          DRIVE_SUBSYSTEM_3_DOC_QEP_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_QEP_NAME                                 DRIVE_SUBSYSTEM_3_DOC_QEP_NAME
#define DRIVE1_DOC_QEP_SPAN                                 DRIVE_SUBSYSTEM_3_DOC_QEP_SPAN
#define DRIVE1_DOC_QEP_TYPE                                 DRIVE_SUBSYSTEM_3_DOC_QEP_TYPE


/*
 * drive_subsystem_3_DOC_SM configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_DOC_SM                        ALT_MODULE_CLASS_drive_subsystem_3_doc_sm
#define DRIVE1_DOC_SM_BASE                                    DRIVE_SUBSYSTEM_3_DOC_SM_BASE
#define DRIVE1_DOC_SM_IRQ                                     DRIVE_SUBSYSTEM_3_DOC_SM_IRQ
#define DRIVE1_DOC_SM_IRQ_INTERRUPT_CONTROLLER_ID             DRIVE_SUBSYSTEM_3_DOC_SM_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_SM_NAME                                    DRIVE_SUBSYSTEM_3_DOC_SM_NAME
#define DRIVE1_DOC_SM_SPAN                                    DRIVE_SUBSYSTEM_3_DOC_SM_SPAN
#define DRIVE1_DOC_SM_TYPE                                    DRIVE_SUBSYSTEM_3_DOC_SM_TYPE


/*
 * drive_subsystem_3_FOC_Fixp configuration
 *
 */

#define ALT_MODULE_CLASS_drive1_FOC_Fixp                        ALT_MODULE_CLASS_drive_subsystem_3_doc_foc_fixp
#define DRIVE1_FOC_FIXP_BASE                                    DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_BASE
#define DRIVE1_FOC_FIXP_IRQ                                     DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_IRQ
#define DRIVE1_FOC_FIXP_IRQ_INTERRUPT_CONTROLLER_ID             DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_FOC_FIXP_NAME                                    DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_NAME
#define DRIVE1_FOC_FIXP_SPAN                                    DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_SPAN
#define DRIVE1_FOC_FIXP_TYPE                                    DRIVE_SUBSYSTEM_3_DOC_FOC_FIXP_TYPE


/*
 * drive_subsystem_3_doc_rslvr_pio configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_pio
#define ALT_MODULE_CLASS_drive1_doc_rslvr_pio                    ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_pio
#define DRIVE1_DOC_RSLVR_PIO_BASE                                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_BASE
#define DRIVE1_DOC_RSLVR_PIO_BIT_CLEARING_EDGE_REGISTER          DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_BIT_CLEARING_EDGE_REGISTER
#define DRIVE1_DOC_RSLVR_PIO_BIT_MODIFYING_OUTPUT_REGISTER       DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_BIT_MODIFYING_OUTPUT_REGISTER
#define DRIVE1_DOC_RSLVR_PIO_CAPTURE                             DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_CAPTURE
#define DRIVE1_DOC_RSLVR_PIO_DATA_WIDTH                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_DATA_WIDTH
#define DRIVE1_DOC_RSLVR_PIO_DO_TEST_BENCH_WIRING                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_DO_TEST_BENCH_WIRING
#define DRIVE1_DOC_RSLVR_PIO_DRIVEN_SIM_VALUE                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_DRIVEN_SIM_VALUE
#define DRIVE1_DOC_RSLVR_PIO_EDGE_TYPE                           DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_EDGE_TYPE
#define DRIVE1_DOC_RSLVR_PIO_FREQ                                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_FREQ
#define DRIVE1_DOC_RSLVR_PIO_HAS_IN                              DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_HAS_IN
#define DRIVE1_DOC_RSLVR_PIO_HAS_OUT                             DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_HAS_OUT
#define DRIVE1_DOC_RSLVR_PIO_HAS_TRI                             DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_HAS_TRI
#define DRIVE1_DOC_RSLVR_PIO_IRQ                                 DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_IRQ
#define DRIVE1_DOC_RSLVR_PIO_IRQ_INTERRUPT_CONTROLLER_ID         DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_RSLVR_PIO_IRQ_TYPE                            DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_IRQ_TYPE
#define DRIVE1_DOC_RSLVR_PIO_NAME                                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_NAME
#define DRIVE1_DOC_RSLVR_PIO_RESET_VALUE                         DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_RESET_VALUE
#define DRIVE1_DOC_RSLVR_PIO_SPAN                                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_SPAN
#define DRIVE1_DOC_RSLVR_PIO_TYPE                                DRIVE_SUBSYSTEM_3_DOC_RSLVR_PIO_TYPE
#endif

/*
 * drive_subsystem_3_doc_rslvr_spi_ctrl configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_spi_ctrl
#define ALT_MODULE_CLASS_drive1_doc_rslvr_spi_ctrl              ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_spi_ctrl
#define DRIVE1_DOC_RSLVR_SPI_CTRL_BASE                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_BASE
#define DRIVE1_DOC_RSLVR_SPI_CTRL_CLOCKMULT                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_CLOCKMULT
#define DRIVE1_DOC_RSLVR_SPI_CTRL_CLOCKPHASE                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_CLOCKPHASE
#define DRIVE1_DOC_RSLVR_SPI_CTRL_CLOCKPOLARITY                 DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_CLOCKPOLARITY
#define DRIVE1_DOC_RSLVR_SPI_CTRL_CLOCKUNITS                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_CLOCKUNITS
#define DRIVE1_DOC_RSLVR_SPI_CTRL_DATABITS                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_DATABITS
#define DRIVE1_DOC_RSLVR_SPI_CTRL_DATAWIDTH                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_DATAWIDTH
#define DRIVE1_DOC_RSLVR_SPI_CTRL_DELAYMULT                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_DELAYMULT
#define DRIVE1_DOC_RSLVR_SPI_CTRL_DELAYUNITS                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_DELAYUNITS
#define DRIVE1_DOC_RSLVR_SPI_CTRL_EXTRADELAY                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_EXTRADELAY
#define DRIVE1_DOC_RSLVR_SPI_CTRL_INSERT_SYNC                   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_INSERT_SYNC
#define DRIVE1_DOC_RSLVR_SPI_CTRL_IRQ                           DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_IRQ
#define DRIVE1_DOC_RSLVR_SPI_CTRL_IRQ_INTERRUPT_CONTROLLER_ID   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_RSLVR_SPI_CTRL_ISMASTER                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_ISMASTER
#define DRIVE1_DOC_RSLVR_SPI_CTRL_LSBFIRST                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_LSBFIRST
#define DRIVE1_DOC_RSLVR_SPI_CTRL_NAME                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_NAME
#define DRIVE1_DOC_RSLVR_SPI_CTRL_NUMSLAVES                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_NUMSLAVES
#define DRIVE1_DOC_RSLVR_SPI_CTRL_PREFIX                        DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_PREFIX
#define DRIVE1_DOC_RSLVR_SPI_CTRL_SPAN                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_SPAN
#define DRIVE1_DOC_RSLVR_SPI_CTRL_SYNC_REG_DEPTH                DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_SYNC_REG_DEPTH
#define DRIVE1_DOC_RSLVR_SPI_CTRL_TARGETCLOCK                   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_TARGETCLOCK
#define DRIVE1_DOC_RSLVR_SPI_CTRL_TARGETSSDELAY                 DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_TARGETSSDELAY
#define DRIVE1_DOC_RSLVR_SPI_CTRL_TYPE                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_CTRL_TYPE
#endif

/*
 * drive_subsystem_3_doc_rslvr_spi_posn configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_spi_posn
#define ALT_MODULE_CLASS_drive1_doc_rslvr_spi_posn              ALT_MODULE_CLASS_drive_subsystem_3_doc_rslvr_spi_posn
#define DRIVE1_DOC_RSLVR_SPI_POSN_BASE                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_BASE
#define DRIVE1_DOC_RSLVR_SPI_POSN_CLOCKMULT                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_CLOCKMULT
#define DRIVE1_DOC_RSLVR_SPI_POSN_CLOCKPHASE                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_CLOCKPHASE
#define DRIVE1_DOC_RSLVR_SPI_POSN_CLOCKPOLARITY                 DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_CLOCKPOLARITY
#define DRIVE1_DOC_RSLVR_SPI_POSN_CLOCKUNITS                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_CLOCKUNITS
#define DRIVE1_DOC_RSLVR_SPI_POSN_DATABITS                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_DATABITS
#define DRIVE1_DOC_RSLVR_SPI_POSN_DATAWIDTH                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_DATAWIDTH
#define DRIVE1_DOC_RSLVR_SPI_POSN_DELAYMULT                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_DELAYMULT
#define DRIVE1_DOC_RSLVR_SPI_POSN_DELAYUNITS                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_DELAYUNITS
#define DRIVE1_DOC_RSLVR_SPI_POSN_EXTRADELAY                    DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_EXTRADELAY
#define DRIVE1_DOC_RSLVR_SPI_POSN_INSERT_SYNC                   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_INSERT_SYNC
#define DRIVE1_DOC_RSLVR_SPI_POSN_IRQ                           DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_IRQ
#define DRIVE1_DOC_RSLVR_SPI_POSN_IRQ_INTERRUPT_CONTROLLER_ID   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_DOC_RSLVR_SPI_POSN_ISMASTER                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_ISMASTER
#define DRIVE1_DOC_RSLVR_SPI_POSN_LSBFIRST                      DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_LSBFIRST
#define DRIVE1_DOC_RSLVR_SPI_POSN_NAME                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_NAME
#define DRIVE1_DOC_RSLVR_SPI_POSN_NUMSLAVES                     DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_NUMSLAVES
#define DRIVE1_DOC_RSLVR_SPI_POSN_PREFIX                        DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_PREFIX
#define DRIVE1_DOC_RSLVR_SPI_POSN_SPAN                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_SPAN
#define DRIVE1_DOC_RSLVR_SPI_POSN_SYNC_REG_DEPTH                DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_SYNC_REG_DEPTH
#define DRIVE1_DOC_RSLVR_SPI_POSN_TARGETCLOCK                   DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_TARGETCLOCK
#define DRIVE1_DOC_RSLVR_SPI_POSN_TARGETSSDELAY                 DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_TARGETSSDELAY
#define DRIVE1_DOC_RSLVR_SPI_POSN_TYPE                          DRIVE_SUBSYSTEM_3_DOC_RSLVR_SPI_POSN_TYPE
#endif

/*
 * drive_subsystem_3_hall_pio configuration
 *
 */
#ifdef ALT_MODULE_CLASS_drive_subsystem_3_hall_pio
#define ALT_MODULE_CLASS_drive1_hall_pio                ALT_MODULE_CLASS_drive_subsystem_3_hall_pio
#define DRIVE1_HALL_PIO_BASE                            DRIVE_SUBSYSTEM_3_HALL_PIO_BASE
#define DRIVE1_HALL_PIO_BIT_CLEARING_EDGE_REGISTER      DRIVE_SUBSYSTEM_3_HALL_PIO_BIT_CLEARING_EDGE_REGISTER
#define DRIVE1_HALL_PIO_BIT_MODIFYING_OUTPUT_REGISTER   DRIVE_SUBSYSTEM_3_HALL_PIO_BIT_MODIFYING_OUTPUT_REGISTER
#define DRIVE1_HALL_PIO_CAPTURE                         DRIVE_SUBSYSTEM_3_HALL_PIO_CAPTURE
#define DRIVE1_HALL_PIO_DATA_WIDTH                      DRIVE_SUBSYSTEM_3_HALL_PIO_DATA_WIDTH
#define DRIVE1_HALL_PIO_DO_TEST_BENCH_WIRING            DRIVE_SUBSYSTEM_3_HALL_PIO_DO_TEST_BENCH_WIRING
#define DRIVE1_HALL_PIO_DRIVEN_SIM_VALUE                DRIVE_SUBSYSTEM_3_HALL_PIO_DRIVEN_SIM_VALUE
#define DRIVE1_HALL_PIO_EDGE_TYPE                       DRIVE_SUBSYSTEM_3_HALL_PIO_EDGE_TYPE
#define DRIVE1_HALL_PIO_FREQ                            DRIVE_SUBSYSTEM_3_HALL_PIO_FREQ
#define DRIVE1_HALL_PIO_HAS_IN                          DRIVE_SUBSYSTEM_3_HALL_PIO_HAS_IN
#define DRIVE1_HALL_PIO_HAS_OUT                         DRIVE_SUBSYSTEM_3_HALL_PIO_HAS_OUT
#define DRIVE1_HALL_PIO_HAS_TRI                         DRIVE_SUBSYSTEM_3_HALL_PIO_HAS_TRI
#define DRIVE1_HALL_PIO_IRQ                             DRIVE_SUBSYSTEM_3_HALL_PIO_IRQ
#define DRIVE1_HALL_PIO_IRQ_INTERRUPT_CONTROLLER_ID     DRIVE_SUBSYSTEM_3_HALL_PIO_IRQ_INTERRUPT_CONTROLLER_ID
#define DRIVE1_HALL_PIO_IRQ_TYPE                        DRIVE_SUBSYSTEM_3_HALL_PIO_IRQ_TYPE
#define DRIVE1_HALL_PIO_NAME                            DRIVE_SUBSYSTEM_3_HALL_PIO_NAME
#define DRIVE1_HALL_PIO_RESET_VALUE                     DRIVE_SUBSYSTEM_3_HALL_PIO_RESET_VALUE
#define DRIVE1_HALL_PIO_SPAN                            DRIVE_SUBSYSTEM_3_HALL_PIO_SPAN
#define DRIVE1_HALL_PIO_TYPE                            DRIVE_SUBSYSTEM_3_HALL_PIO_TYPE
#endif

/*
 * motor_model_subsystem_2_motor_model configuration
 *
 */

#define ALT_MODULE_CLASS_motor_kit_sim_20MHz_MotorModel_0               ALT_MODULE_CLASS_motor_model_subsystem_2_motor_model
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_BASE                           MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_BASE
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_IRQ                            MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_IRQ
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_IRQ_INTERRUPT_CONTROLLER_ID    MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_IRQ_INTERRUPT_CONTROLLER_ID
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_NAME                           MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_NAME
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_SPAN                           MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_SPAN
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_0_TYPE                           MOTOR_MODEL_SUBSYSTEM_2_MOTOR_MODEL_TYPE

/*
 * motor_model_subsystem_3_motor_model configuration
 *
 */

#define ALT_MODULE_CLASS_motor_kit_sim_20MHz_MotorModel_1               ALT_MODULE_CLASS_motor_model_subsystem_3_motor_model
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_BASE                           MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_BASE
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_IRQ                            MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_IRQ
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_IRQ_INTERRUPT_CONTROLLER_ID    MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_IRQ_INTERRUPT_CONTROLLER_ID
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_NAME                           MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_NAME
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_SPAN                           MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_SPAN
#define MOTOR_KIT_SIM_20MHZ_MOTORMODEL_1_TYPE                           MOTOR_MODEL_SUBSYSTEM_3_MOTOR_MODEL_TYPE

/*
 * dummy IO buttons configuration
 *
 */
#define IO_IN_BUTTONS_BASE                    0x00000000

#endif /* __SYSTEM_SHIM_H_ */
